[algokit]
min_version = "v2.6.0"

[generate.smart-contract]
description = "Generate a new smart contract for existing project"
path = ".algokit/generators/create_contract"

[generate.env-file]
description = "Generate a new generic or Algorand network specific .env file"
path = ".algokit/generators/create_env_file"

[project]
type = 'contract'
name = 'smart-contract'
artifacts = 'smart_contracts/artifacts'

[project.deploy]
command = "npm run deploy:ci"
network = "testnet"  # 👈 important

[project.deploy.testnet]
environment_secrets = [
  "DEPLOYER_MNEMONIC",
]

[project.deploy.mainnet]
environment_secrets = [
  "DEPLOYER_MNEMONIC",
]

[project.run]
build = { commands = ['npm run build'], description = 'Build all smart contracts in the project' }
audit-teal = { commands = [
  'algokit task analyze smart_contracts/artifacts --recursive --force --exclude rekey-to --exclude is-updatable --exclude missing-fee-check --exclude is-deletable --exclude can-close-asset --exclude can-close-account --exclude unprotected-deletable --exclude unprotected-updatable',
], description = 'Audit TEAL files' }

ci-teal-diff = { commands = [
  'git add -N ./smart_contracts/artifacts',
  'git diff --exit-code --minimal ./smart_contracts/artifacts',
], description = 'Check TEAL files for differences' }
